server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: turight-education-awards-backend

firebase:
  project-id: turight-national-education-awa
  credentials:
    path: classpath:firebase-service-account.json

management:
  endpoints:
    web:
      exposure:
        include: health,info
